name: Trigger auto deployment for container-app-shbw3uyuk73ma

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-shbw3uyuk73ma-AutoDeployTrigger-8d2996a4-134e-4d1b-9a23-4046924dcee5.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPSHBW3UYUK73MA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPSHBW3UYUK73MA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPSHBW3UYUK73MA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPSHBW3UYUK73MA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPSHBW3UYUK73MA_REGISTRY_PASSWORD }}
          containerAppName: container-app-shbw3uyuk73ma
          resourceGroup: flaskbasic9759b79b
          imageToBuild: default/container-app-shbw3uyuk73ma:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


